//! Tokens of the Verilog / SystemVerilog lexer.
//!
//! A [`Token`] is a [`TokenKind`] plus a [`Span`]. Kinds that need it carry
//! their text: identifiers keep their name, numbers keep the literal exactly
//! as written (`8'hff`, `1.5e3`, `10ns`) so the parser can hand it to the
//! `logic` value parser later, and strings keep their value with escapes
//! already processed. Keywords and punctuation carry nothing but the
//! [`Keyword`] or [`Punct`] variant.
//!
//! Which words are reserved depends on the language version, so keyword
//! lookup takes a [`Dialect`]: `logic` is a keyword in SystemVerilog and a
//! plain identifier in Verilog-2005. The lookup is a `match` on the text
//! generated by the `keywords!` macro below, which is also the single place a
//! keyword and its minimum dialect are listed.

use std::fmt;

use crate::source::Span;

/// The language version that decides which words are reserved.
///
/// Ordered: a later dialect reserves a superset of the earlier ones' words.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub enum Dialect {
    /// IEEE 1364-2001.
    Verilog2001,
    /// IEEE 1364-2005 (adds `uwire`).
    Verilog2005,
    /// IEEE 1800-2017 SystemVerilog.
    #[default]
    SystemVerilog,
}

impl Dialect {
    /// The dialect conventionally implied by a file extension (`v`, `vh`
    /// give Verilog-2005; `sv`, `svh` give SystemVerilog).
    pub fn for_extension(ext: &str) -> Option<Dialect> {
        match ext.to_ascii_lowercase().as_str() {
            "v" | "vh" => Some(Dialect::Verilog2005),
            "sv" | "svh" => Some(Dialect::SystemVerilog),
            _ => None,
        }
    }

    /// The dialect selected by a `` `begin_keywords `` version string such as
    /// `1364-2005` or `1800-2017`.
    pub fn for_keywords_spec(spec: &str) -> Option<Dialect> {
        match spec {
            "1364-1995" | "1364-2001" | "1364-2001-noconfig" => Some(Dialect::Verilog2001),
            "1364-2005" => Some(Dialect::Verilog2005),
            "1800-2005" | "1800-2009" | "1800-2012" | "1800-2017" | "1800-2023" => {
                Some(Dialect::SystemVerilog)
            }
            _ => None,
        }
    }
}

impl fmt::Display for Dialect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Dialect::Verilog2001 => "Verilog-2001",
            Dialect::Verilog2005 => "Verilog-2005",
            Dialect::SystemVerilog => "SystemVerilog",
        })
    }
}

/// Defines [`Keyword`] from one table of `Variant => "text", MinimumDialect`.
macro_rules! keywords {
    ($( $variant:ident => $text:literal, $min:ident; )*) => {
        /// A reserved word.
        ///
        /// Each variant documents its spelling; see [`Keyword::lookup`] for
        /// the dialect in which it becomes reserved.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
        #[allow(missing_docs)]
        pub enum Keyword {
            $( #[doc = concat!("`", $text, "`")] $variant, )*
        }

        impl Keyword {
            /// Every keyword, in table order.
            pub const ALL: &[Keyword] = &[ $( Keyword::$variant, )* ];

            /// The spelling of the keyword.
            pub fn as_str(self) -> &'static str {
                match self {
                    $( Keyword::$variant => $text, )*
                }
            }

            /// The earliest dialect in which the word is reserved.
            pub fn since(self) -> Dialect {
                match self {
                    $( Keyword::$variant => Dialect::$min, )*
                }
            }

            /// Looks a word up, returning `None` when it is not reserved in
            /// `dialect`.
            pub fn lookup(text: &str, dialect: Dialect) -> Option<Keyword> {
                let kw = match text {
                    $( $text => Keyword::$variant, )*
                    _ => return None,
                };
                (dialect >= kw.since()).then_some(kw)
            }
        }
    };
}

keywords! {
    // IEEE 1364-2001, Annex B.
    Always => "always", Verilog2001;
    And => "and", Verilog2001;
    Assign => "assign", Verilog2001;
    Automatic => "automatic", Verilog2001;
    Begin => "begin", Verilog2001;
    Buf => "buf", Verilog2001;
    Bufif0 => "bufif0", Verilog2001;
    Bufif1 => "bufif1", Verilog2001;
    Case => "case", Verilog2001;
    Casex => "casex", Verilog2001;
    Casez => "casez", Verilog2001;
    Cell => "cell", Verilog2001;
    Cmos => "cmos", Verilog2001;
    Config => "config", Verilog2001;
    Deassign => "deassign", Verilog2001;
    Default => "default", Verilog2001;
    Defparam => "defparam", Verilog2001;
    Design => "design", Verilog2001;
    Disable => "disable", Verilog2001;
    Edge => "edge", Verilog2001;
    Else => "else", Verilog2001;
    End => "end", Verilog2001;
    Endcase => "endcase", Verilog2001;
    Endconfig => "endconfig", Verilog2001;
    Endfunction => "endfunction", Verilog2001;
    Endgenerate => "endgenerate", Verilog2001;
    Endmodule => "endmodule", Verilog2001;
    Endprimitive => "endprimitive", Verilog2001;
    Endspecify => "endspecify", Verilog2001;
    Endtable => "endtable", Verilog2001;
    Endtask => "endtask", Verilog2001;
    Event => "event", Verilog2001;
    For => "for", Verilog2001;
    Force => "force", Verilog2001;
    Forever => "forever", Verilog2001;
    Fork => "fork", Verilog2001;
    Function => "function", Verilog2001;
    Generate => "generate", Verilog2001;
    Genvar => "genvar", Verilog2001;
    Highz0 => "highz0", Verilog2001;
    Highz1 => "highz1", Verilog2001;
    If => "if", Verilog2001;
    Ifnone => "ifnone", Verilog2001;
    Incdir => "incdir", Verilog2001;
    Include => "include", Verilog2001;
    Initial => "initial", Verilog2001;
    Inout => "inout", Verilog2001;
    Input => "input", Verilog2001;
    Instance => "instance", Verilog2001;
    Integer => "integer", Verilog2001;
    Join => "join", Verilog2001;
    Large => "large", Verilog2001;
    Liblist => "liblist", Verilog2001;
    Library => "library", Verilog2001;
    Localparam => "localparam", Verilog2001;
    Macromodule => "macromodule", Verilog2001;
    Medium => "medium", Verilog2001;
    Module => "module", Verilog2001;
    Nand => "nand", Verilog2001;
    Negedge => "negedge", Verilog2001;
    Nmos => "nmos", Verilog2001;
    Nor => "nor", Verilog2001;
    Noshowcancelled => "noshowcancelled", Verilog2001;
    Not => "not", Verilog2001;
    Notif0 => "notif0", Verilog2001;
    Notif1 => "notif1", Verilog2001;
    Or => "or", Verilog2001;
    Output => "output", Verilog2001;
    Parameter => "parameter", Verilog2001;
    Pmos => "pmos", Verilog2001;
    Posedge => "posedge", Verilog2001;
    Primitive => "primitive", Verilog2001;
    Pull0 => "pull0", Verilog2001;
    Pull1 => "pull1", Verilog2001;
    Pulldown => "pulldown", Verilog2001;
    Pullup => "pullup", Verilog2001;
    PulsestyleOnevent => "pulsestyle_onevent", Verilog2001;
    PulsestyleOndetect => "pulsestyle_ondetect", Verilog2001;
    Rcmos => "rcmos", Verilog2001;
    Real => "real", Verilog2001;
    Realtime => "realtime", Verilog2001;
    Reg => "reg", Verilog2001;
    Release => "release", Verilog2001;
    Repeat => "repeat", Verilog2001;
    Rnmos => "rnmos", Verilog2001;
    Rpmos => "rpmos", Verilog2001;
    Rtran => "rtran", Verilog2001;
    Rtranif0 => "rtranif0", Verilog2001;
    Rtranif1 => "rtranif1", Verilog2001;
    Scalared => "scalared", Verilog2001;
    Showcancelled => "showcancelled", Verilog2001;
    Signed => "signed", Verilog2001;
    Small => "small", Verilog2001;
    Specify => "specify", Verilog2001;
    Specparam => "specparam", Verilog2001;
    Strong0 => "strong0", Verilog2001;
    Strong1 => "strong1", Verilog2001;
    Supply0 => "supply0", Verilog2001;
    Supply1 => "supply1", Verilog2001;
    Table => "table", Verilog2001;
    Task => "task", Verilog2001;
    Time => "time", Verilog2001;
    Tran => "tran", Verilog2001;
    Tranif0 => "tranif0", Verilog2001;
    Tranif1 => "tranif1", Verilog2001;
    Tri => "tri", Verilog2001;
    Tri0 => "tri0", Verilog2001;
    Tri1 => "tri1", Verilog2001;
    Triand => "triand", Verilog2001;
    Trior => "trior", Verilog2001;
    Trireg => "trireg", Verilog2001;
    Unsigned => "unsigned", Verilog2001;
    Use => "use", Verilog2001;
    Vectored => "vectored", Verilog2001;
    Wait => "wait", Verilog2001;
    Wand => "wand", Verilog2001;
    Weak0 => "weak0", Verilog2001;
    Weak1 => "weak1", Verilog2001;
    While => "while", Verilog2001;
    Wire => "wire", Verilog2001;
    Wor => "wor", Verilog2001;
    Xnor => "xnor", Verilog2001;
    Xor => "xor", Verilog2001;
    // IEEE 1364-2005.
    Uwire => "uwire", Verilog2005;
    // IEEE 1800-2017, Annex B.
    AcceptOn => "accept_on", SystemVerilog;
    Alias => "alias", SystemVerilog;
    AlwaysComb => "always_comb", SystemVerilog;
    AlwaysFf => "always_ff", SystemVerilog;
    AlwaysLatch => "always_latch", SystemVerilog;
    Assert => "assert", SystemVerilog;
    Assume => "assume", SystemVerilog;
    Before => "before", SystemVerilog;
    Bind => "bind", SystemVerilog;
    Bins => "bins", SystemVerilog;
    Binsof => "binsof", SystemVerilog;
    Bit => "bit", SystemVerilog;
    Break => "break", SystemVerilog;
    Byte => "byte", SystemVerilog;
    Chandle => "chandle", SystemVerilog;
    Checker => "checker", SystemVerilog;
    Class => "class", SystemVerilog;
    Clocking => "clocking", SystemVerilog;
    Const => "const", SystemVerilog;
    Constraint => "constraint", SystemVerilog;
    Context => "context", SystemVerilog;
    Continue => "continue", SystemVerilog;
    Cover => "cover", SystemVerilog;
    Covergroup => "covergroup", SystemVerilog;
    Coverpoint => "coverpoint", SystemVerilog;
    Cross => "cross", SystemVerilog;
    Dist => "dist", SystemVerilog;
    Do => "do", SystemVerilog;
    Endchecker => "endchecker", SystemVerilog;
    Endclass => "endclass", SystemVerilog;
    Endclocking => "endclocking", SystemVerilog;
    Endgroup => "endgroup", SystemVerilog;
    Endinterface => "endinterface", SystemVerilog;
    Endpackage => "endpackage", SystemVerilog;
    Endprogram => "endprogram", SystemVerilog;
    Endproperty => "endproperty", SystemVerilog;
    Endsequence => "endsequence", SystemVerilog;
    Enum => "enum", SystemVerilog;
    Eventually => "eventually", SystemVerilog;
    Expect => "expect", SystemVerilog;
    Export => "export", SystemVerilog;
    Extends => "extends", SystemVerilog;
    Extern => "extern", SystemVerilog;
    Final => "final", SystemVerilog;
    FirstMatch => "first_match", SystemVerilog;
    Foreach => "foreach", SystemVerilog;
    Forkjoin => "forkjoin", SystemVerilog;
    Global => "global", SystemVerilog;
    Iff => "iff", SystemVerilog;
    IgnoreBins => "ignore_bins", SystemVerilog;
    IllegalBins => "illegal_bins", SystemVerilog;
    Implements => "implements", SystemVerilog;
    Implies => "implies", SystemVerilog;
    Import => "import", SystemVerilog;
    Inside => "inside", SystemVerilog;
    Int => "int", SystemVerilog;
    Interconnect => "interconnect", SystemVerilog;
    Interface => "interface", SystemVerilog;
    Intersect => "intersect", SystemVerilog;
    JoinAny => "join_any", SystemVerilog;
    JoinNone => "join_none", SystemVerilog;
    Let => "let", SystemVerilog;
    Local => "local", SystemVerilog;
    Logic => "logic", SystemVerilog;
    Longint => "longint", SystemVerilog;
    Matches => "matches", SystemVerilog;
    Modport => "modport", SystemVerilog;
    Nettype => "nettype", SystemVerilog;
    New => "new", SystemVerilog;
    Nexttime => "nexttime", SystemVerilog;
    Null => "null", SystemVerilog;
    Package => "package", SystemVerilog;
    Packed => "packed", SystemVerilog;
    Priority => "priority", SystemVerilog;
    Program => "program", SystemVerilog;
    Property => "property", SystemVerilog;
    Protected => "protected", SystemVerilog;
    Pure => "pure", SystemVerilog;
    Rand => "rand", SystemVerilog;
    Randc => "randc", SystemVerilog;
    Randcase => "randcase", SystemVerilog;
    Randsequence => "randsequence", SystemVerilog;
    Ref => "ref", SystemVerilog;
    RejectOn => "reject_on", SystemVerilog;
    Restrict => "restrict", SystemVerilog;
    Return => "return", SystemVerilog;
    SAlways => "s_always", SystemVerilog;
    SEventually => "s_eventually", SystemVerilog;
    SNexttime => "s_nexttime", SystemVerilog;
    SUntil => "s_until", SystemVerilog;
    SUntilWith => "s_until_with", SystemVerilog;
    Sequence => "sequence", SystemVerilog;
    Shortint => "shortint", SystemVerilog;
    Shortreal => "shortreal", SystemVerilog;
    Soft => "soft", SystemVerilog;
    Solve => "solve", SystemVerilog;
    Static => "static", SystemVerilog;
    String => "string", SystemVerilog;
    Strong => "strong", SystemVerilog;
    Struct => "struct", SystemVerilog;
    Super => "super", SystemVerilog;
    SyncAcceptOn => "sync_accept_on", SystemVerilog;
    SyncRejectOn => "sync_reject_on", SystemVerilog;
    Tagged => "tagged", SystemVerilog;
    This => "this", SystemVerilog;
    Throughout => "throughout", SystemVerilog;
    Timeprecision => "timeprecision", SystemVerilog;
    Timeunit => "timeunit", SystemVerilog;
    Type => "type", SystemVerilog;
    Typedef => "typedef", SystemVerilog;
    Union => "union", SystemVerilog;
    Unique => "unique", SystemVerilog;
    Unique0 => "unique0", SystemVerilog;
    Until => "until", SystemVerilog;
    UntilWith => "until_with", SystemVerilog;
    Untyped => "untyped", SystemVerilog;
    Var => "var", SystemVerilog;
    Virtual => "virtual", SystemVerilog;
    Void => "void", SystemVerilog;
    WaitOrder => "wait_order", SystemVerilog;
    Weak => "weak", SystemVerilog;
    Wildcard => "wildcard", SystemVerilog;
    With => "with", SystemVerilog;
    Within => "within", SystemVerilog;
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Defines [`Punct`] from one table of `Variant => "text"`.
///
/// The lexer matches punctuation longest-first by its own logic; this table
/// only names the variants and their spelling.
macro_rules! puncts {
    ($( $(#[$meta:meta])* $variant:ident => $text:literal; )*) => {
        /// An operator or delimiter.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
        #[allow(missing_docs)]
        pub enum Punct {
            $( #[doc = concat!("`", $text, "`")] $(#[$meta])* $variant, )*
        }

        impl Punct {
            /// Every punctuation token, in table order.
            pub const ALL: &[Punct] = &[ $( Punct::$variant, )* ];

            /// The spelling of the token.
            pub fn as_str(self) -> &'static str {
                match self {
                    $( Punct::$variant => $text, )*
                }
            }
        }
    };
}

puncts! {
    LParen => "(";
    RParen => ")";
    LBracket => "[";
    RBracket => "]";
    LBrace => "{";
    RBrace => "}";
    Semi => ";";
    Comma => ",";
    Dot => ".";
    Colon => ":";
    Question => "?";
    Bang => "!";
    Tilde => "~";
    Amp => "&";
    Pipe => "|";
    Caret => "^";
    Plus => "+";
    Minus => "-";
    Star => "*";
    Slash => "/";
    Percent => "%";
    Lt => "<";
    Gt => ">";
    Eq => "=";
    Hash => "#";
    At => "@";
    Dollar => "$";
    /// A lone `'`, as in the cast `int'(x)`.
    Apostrophe => "'";
    /// `'{`, opening an assignment pattern.
    ApostropheBrace => "'{";
    AttrOpen => "(*";
    AttrClose => "*)";
    Shl => "<<";
    Shr => ">>";
    Ashl => "<<<";
    Ashr => ">>>";
    EqEq => "==";
    BangEq => "!=";
    CaseEq => "===";
    CaseNe => "!==";
    WildEq => "==?";
    WildNe => "!=?";
    Le => "<=";
    Ge => ">=";
    AndAnd => "&&";
    OrOr => "||";
    AndAndAnd => "&&&";
    Arrow => "->";
    Equiv => "<->";
    ArrowArrow => "->>";
    EqGt => "=>";
    StarGt => "*>";
    ColonColon => "::";
    ColonEq => ":=";
    ColonSlash => ":/";
    PlusPlus => "++";
    MinusMinus => "--";
    PlusEq => "+=";
    MinusEq => "-=";
    StarEq => "*=";
    SlashEq => "/=";
    PercentEq => "%=";
    AmpEq => "&=";
    PipeEq => "|=";
    CaretEq => "^=";
    ShlEq => "<<=";
    ShrEq => ">>=";
    AshlEq => "<<<=";
    AshrEq => ">>>=";
    StarStar => "**";
    TildeAmp => "~&";
    TildePipe => "~|";
    TildeCaret => "~^";
    CaretTilde => "^~";
    HashHash => "##";
    PlusColon => "+:";
    MinusColon => "-:";
    DotStar => ".*";
    /// `|->`, overlapping implication.
    ImplyOverlap => "|->";
    /// `|=>`, non-overlapping implication.
    ImplyNext => "|=>";
    /// `#-#`, sequence property follows.
    HashMinusHash => "#-#";
    /// `#=#`, sequence property follows (non-overlapping).
    HashEqHash => "#=#";
    AtAt => "@@";
}

impl fmt::Display for Punct {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// What kind of token was lexed, with its text where that matters.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum TokenKind {
    /// A simple identifier such as `clk` or `data_$1`.
    Ident {
        /// The identifier.
        name: String,
    },
    /// A backslash-escaped identifier such as `\bus[0]`, stored without the
    /// backslash. Escaped identifiers are never keywords.
    EscapedIdent {
        /// The identifier without its leading backslash.
        name: String,
    },
    /// A `$`-prefixed system task, function or scope name such as
    /// `$display`, stored without the `$`.
    SystemIdent {
        /// The name without its leading `$`.
        name: String,
    },
    /// A numeric literal kept as written: decimal, based (`8'hff`), real
    /// (`1.5e3`), unsized (`'0`, `'x`) or time (`10ns`, `1step`).
    Number {
        /// The literal text, exactly as in the source.
        text: String,
    },
    /// A string literal with escape sequences already decoded.
    Str {
        /// The decoded value.
        value: String,
    },
    /// A reserved word.
    Keyword(Keyword),
    /// An operator or delimiter.
    Punct(Punct),
    /// A compiler directive the preprocessor passed through for the parser,
    /// such as `` `default_nettype `` or `` `timescale ``, without the
    /// backtick.
    Directive {
        /// The directive name without its leading backtick.
        name: String,
    },
    /// End of input; always the last token.
    Eof,
    /// Text the lexer could not tokenise. A diagnostic was already reported,
    /// so later stages should skip it silently.
    Error {
        /// The offending text.
        text: String,
    },
}

impl TokenKind {
    /// True for [`TokenKind::Keyword`].
    pub fn is_keyword(&self) -> bool {
        matches!(self, TokenKind::Keyword(_))
    }

    /// True when the token is this particular keyword.
    pub fn is_kw(&self, kw: Keyword) -> bool {
        matches!(self, TokenKind::Keyword(k) if *k == kw)
    }

    /// True when the token is this particular punctuation.
    pub fn is_punct(&self, p: Punct) -> bool {
        matches!(self, TokenKind::Punct(q) if *q == p)
    }

    /// True for simple and escaped identifiers.
    pub fn is_ident(&self) -> bool {
        matches!(
            self,
            TokenKind::Ident { .. } | TokenKind::EscapedIdent { .. }
        )
    }

    /// The identifier name of a simple or escaped identifier.
    pub fn ident_name(&self) -> Option<&str> {
        match self {
            TokenKind::Ident { name } | TokenKind::EscapedIdent { name } => Some(name),
            _ => None,
        }
    }

    /// A short lowercase name of the kind, for token dumps and tests:
    /// `ident`, `escaped`, `system`, `number`, `string`, `keyword`, `punct`,
    /// `directive`, `eof` or `error`.
    pub fn kind_name(&self) -> &'static str {
        match self {
            TokenKind::Ident { .. } => "ident",
            TokenKind::EscapedIdent { .. } => "escaped",
            TokenKind::SystemIdent { .. } => "system",
            TokenKind::Number { .. } => "number",
            TokenKind::Str { .. } => "string",
            TokenKind::Keyword(_) => "keyword",
            TokenKind::Punct(_) => "punct",
            TokenKind::Directive { .. } => "directive",
            TokenKind::Eof => "eof",
            TokenKind::Error { .. } => "error",
        }
    }

    /// The text carried by the token: the name, literal text, decoded string
    /// value or spelling. Empty for [`TokenKind::Eof`].
    pub fn text(&self) -> &str {
        match self {
            TokenKind::Ident { name }
            | TokenKind::EscapedIdent { name }
            | TokenKind::SystemIdent { name }
            | TokenKind::Directive { name } => name,
            TokenKind::Number { text } | TokenKind::Error { text } => text,
            TokenKind::Str { value } => value,
            TokenKind::Keyword(kw) => kw.as_str(),
            TokenKind::Punct(p) => p.as_str(),
            TokenKind::Eof => "",
        }
    }
}

impl fmt::Display for TokenKind {
    /// Describes the token the way an "expected X, found Y" message wants
    /// it: keywords and punctuation in backticks, other kinds by category.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Ident { name } => write!(f, "identifier `{name}`"),
            TokenKind::EscapedIdent { name } => write!(f, "identifier `\\{name}`"),
            TokenKind::SystemIdent { name } => write!(f, "system identifier `${name}`"),
            TokenKind::Number { text } => write!(f, "number `{text}`"),
            TokenKind::Str { .. } => f.write_str("string literal"),
            TokenKind::Keyword(kw) => write!(f, "`{kw}`"),
            TokenKind::Punct(p) => write!(f, "`{p}`"),
            TokenKind::Directive { name } => write!(f, "directive `` `{name} ``"),
            TokenKind::Eof => f.write_str("end of file"),
            TokenKind::Error { text } => write!(f, "invalid token `{text}`"),
        }
    }
}

/// One lexed token and where it came from.
///
/// For text produced by a macro expansion the span covers the macro use
/// site in the original file, not the definition; see
/// [`crate::verilog::preprocess`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    /// What was lexed.
    pub kind: TokenKind,
    /// Where it was lexed from.
    pub span: Span,
}

impl Token {
    /// Builds a token.
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Token { kind, span }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keywords_are_dialect_gated() {
        assert_eq!(
            Keyword::lookup("module", Dialect::Verilog2001),
            Some(Keyword::Module)
        );
        assert_eq!(Keyword::lookup("logic", Dialect::Verilog2005), None);
        assert_eq!(
            Keyword::lookup("logic", Dialect::SystemVerilog),
            Some(Keyword::Logic)
        );
        assert_eq!(Keyword::lookup("uwire", Dialect::Verilog2001), None);
        assert_eq!(
            Keyword::lookup("uwire", Dialect::Verilog2005),
            Some(Keyword::Uwire)
        );
        assert_eq!(Keyword::lookup("Module", Dialect::SystemVerilog), None);
        assert_eq!(Keyword::lookup("", Dialect::SystemVerilog), None);
    }

    #[test]
    fn tables_round_trip_and_are_unique() {
        for &kw in Keyword::ALL {
            assert_eq!(
                Keyword::lookup(kw.as_str(), Dialect::SystemVerilog),
                Some(kw)
            );
        }
        let mut texts: Vec<_> = Punct::ALL.iter().map(|p| p.as_str()).collect();
        texts.sort_unstable();
        texts.dedup();
        assert_eq!(texts.len(), Punct::ALL.len());
    }

    #[test]
    fn display_and_text() {
        let id = TokenKind::Ident { name: "clk".into() };
        assert_eq!(id.to_string(), "identifier `clk`");
        assert_eq!(id.text(), "clk");
        assert_eq!(id.kind_name(), "ident");
        assert!(id.is_ident());
        assert_eq!(id.ident_name(), Some("clk"));
        assert_eq!(TokenKind::Keyword(Keyword::Module).to_string(), "`module`");
        assert!(TokenKind::Keyword(Keyword::Module).is_kw(Keyword::Module));
        assert_eq!(TokenKind::Punct(Punct::Ashr).to_string(), "`>>>`");
        assert!(TokenKind::Punct(Punct::Ashr).is_punct(Punct::Ashr));
        assert_eq!(TokenKind::Eof.to_string(), "end of file");
        assert_eq!(TokenKind::Eof.text(), "");
        assert_eq!(
            TokenKind::SystemIdent {
                name: "display".into()
            }
            .to_string(),
            "system identifier `$display`"
        );
    }

    #[test]
    fn dialect_helpers() {
        assert_eq!(Dialect::for_extension("SV"), Some(Dialect::SystemVerilog));
        assert_eq!(Dialect::for_extension("v"), Some(Dialect::Verilog2005));
        assert_eq!(Dialect::for_extension("vhd"), None);
        assert_eq!(
            Dialect::for_keywords_spec("1800-2012"),
            Some(Dialect::SystemVerilog)
        );
        assert_eq!(Dialect::for_keywords_spec("1999"), None);
        assert!(Dialect::Verilog2001 < Dialect::SystemVerilog);
    }
}
