# OpenROAD script for `shifter`, generated by Reticle.
#
# Targets the OpenROAD app (2.0 series command set). Run it from the
# directory holding the generated files:
#
#   openroad -no_init -exit shifter.tcl
#
# The LEF and Liberty paths below are the ones the caller named; they
# come from the PDK, not from Reticle.

read_lef reticle_sc.lef
read_liberty reticle_sc.lib
read_verilog shifter.v
link_design shifter
read_sdc shifter.sdc

# --- floorplan ---
initialize_floorplan -die_area {0 0 30 30} -core_area {2.76 2.76 27.24 27.24} -site retihd
make_tracks
place_pins -hor_layers met1 -ver_layers li1

# --- placement ---
set_wire_rc -layer met2
global_placement -density 0.6
estimate_parasitics -placement
repair_design
detailed_placement
check_placement -verbose

# --- clock tree ---
clock_tree_synthesis -buf_list {BUF_X2 BUF_X4} -root_buf BUF_X2 -sink_clustering_enable
set_propagated_clock [all_clocks]
estimate_parasitics -placement
repair_clock_nets
detailed_placement

# --- routing ---
set_routing_layers -signal li1-met2
global_route -congestion_iterations 30
estimate_parasitics -global_routing
detailed_route -output_drc shifter.drc.rpt -verbose 0

# --- finishing ---
filler_placement {FILL_X1}
check_placement

# --- reports ---
report_design_area
report_checks -path_delay max -format full_clock_expanded
report_checks -path_delay min
report_worst_slack -max
report_tns
report_clock_skew

# --- results ---
write_def shifter.routed.def
write_verilog shifter.routed.v
